import { strToU8, zipSync } from 'fflate';
import { box, meshXml } from './fixtures';
const ns = 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02';
const model = (content: string) => strToU8(`<model xmlns="${ns}" unit="millimeter">${content}</model>`);
const ref = (id: number, instance: number) => `<model_instance><metadata key="object_id" value="${id}"/><metadata key="instance_id" value="${instance}"/><metadata key="identify_id" value="${id * 100 + instance}"/></model_instance>`;
export function nativeFixture(format = 'OrcaSlicer') {
  const plate = (id: number, refs: string) => `<plate><metadata key="plater_id" value="${id}"/><metadata key="plater_name" value="Plate ${id}"/><metadata key="bed_type" value="textured_plate"/>${refs}</plate>`;
  const files = {
    '[Content_Types].xml':strToU8('<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/></Types>'),
    '_rels/.rels':strToU8('<Relationships><Relationship Id="model" Target="/3D/3dmodel.model" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'),
    '3D/_rels/3dmodel.model.rels':strToU8('<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="shared" Target="/3D/Objects/shared.model" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/><Relationship Id="other" Target="/3D/Objects/other.model" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>'),
    '3D/3dmodel.model':strToU8(`<model xmlns="${ns}" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06" requiredextensions="p" unit="millimeter"><metadata name="Application">${format}-2.4.2</metadata><metadata name="BambuStudio:3mfVersion">1</metadata><resources><object id="3" type="model"><components><component p:path="/3D/Objects/shared.model" objectid="1"/><component p:path="/3D/Objects/shared.model" objectid="2"/></components></object><object id="4" type="model"><components><component p:path="/3D/Objects/other.model" objectid="5"/></components></object></resources><build><item objectid="3"/><item objectid="3" transform="1 0 0 0 1 0 0 0 1 120 0 0"/><item objectid="3" transform="1 0 0 0 1 0 0 0 1 155 0 0"/><item objectid="3" transform="1 0 0 0 1 0 0 0 1 175 0 0" printable="0"/><item objectid="3" transform="1 0 0 0 1 0 0 0 1 0 -120 0"/><item objectid="4" transform="1 0 0 0 1 0 0 0 1 120 -120 0"/></build></model>`),
    '3D/Objects/shared.model':model(`<resources><object id="1" type="model">${meshXml(box(20,20,20,20,2)).replace('<triangle ','<triangle paint_color="4" paint_supports="1" paint_seam="8" paint_fuzzy_skin="4" ')}</object><object id="2" type="model">${meshXml(box(25,25,5,5,2))}</object></resources>`),
    '3D/Objects/other.model':model(`<resources><object id="5" type="model">${meshXml(box(60,60,10,10,2))}</object></resources>`),
    'Metadata/model_settings.config':strToU8(`<config><object id="3"><metadata key="name" value="Painted body"/><metadata key="extruder" value="2"/><metadata key="future_setting" value="keep"/><part id="1" subtype="normal_part"><metadata key="name" value="Body"/><metadata key="sparse_infill_density" value="42%"/></part><part id="2" subtype="negative_part"><metadata key="name" value="Cutout"/></part></object><object id="4"><metadata key="name" value="Other plate only"/><part id="5" subtype="normal_part"/></object>${plate(1,ref(3,0))}${plate(2,ref(3,1)+ref(3,2)+ref(3,3))}${plate(3,ref(3,4))}${plate(4,ref(4,0))}<assemble><assemble_item object_id="3" instance_id="1" transform="1 0 0 0 1 0 0 0 1 120 0 0" offset="0 0 0"/></assemble></config>`),
    'Metadata/project_settings.config':strToU8(JSON.stringify({printable_area:['0x0','100x0','100x100','0x100'],initial_layer_print_height:'0.2',brim_type:'no_brim',brim_width:'0',elefant_foot_compensation:'0.2',filament_colour:['#FFFFFF','#FF0000'],filament_type:['PLA','PLA'],wipe_tower_x:['10','15','20','25'],wipe_tower_y:['50','55','60','65'],future_setting:['preserve','all']})),
    'Metadata/layer_heights_profile.txt':strToU8('object_id=1|0;0.2;1;0.2;2;0.2\nobject_id=2|0;0.1;1;0.1;2;0.1\n'),
    'Metadata/layer_config_ranges.xml':strToU8('<objects><object id="1"><range min_z="1" max_z="2"><option opt_key="wall_loops">4</option></range></object><object id="2"><range min_z="1" max_z="2"><option opt_key="wall_loops">8</option></range></object></objects>'),
    'Metadata/custom_gcode_per_layer.xml':strToU8('<custom_gcodes_per_layer><plate><plate_info id="1"/><layer top_z="1" type="4" extruder="1" color="" extra="M117 first"/></plate><plate><plate_info id="2"/><layer top_z="1" type="4" extruder="1" color="" extra="M117 second"/></plate></custom_gcodes_per_layer>'),
    'Metadata/plate_1.gcode':strToU8('old toolpaths'), 'Metadata/plate_2.png':new Uint8Array([1,2,3]), 'Metadata/slice_info.config':strToU8('<config/>'), 'Metadata/opaque.bin':new Uint8Array([2,4,6]),
  };
  return zipSync(files).slice().buffer;
}
