import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { strFromU8, strToU8, unzipSync, zipSync } from 'fflate';
import { exportProject, importProject } from '../src/core/three-mf';
import { generateBrims } from '../src/core/brim';
import { DEFAULT_BRIM } from '../src/core/types';
import { archive, box, meshXml, project } from './fixtures';
import { boundsOf } from '../src/core/geometry';
import { sliceMesh } from '../src/core/mesh';

const slicer = process.env.PRUSA_SLICER || 'C:\\Program Files\\Prusa3D\\PrusaSlicer\\prusa-slicer-console.exe';
describe.skipIf(!existsSync(slicer))('PrusaSlicer integration', () => {
  it('opens a zero-gap brim without fixing missing triangle connections', () => {
    mkdirSync('.local',{recursive:true});
    const p=project([box(-30,10,7,13)]), result=generateBrims(p,{...DEFAULT_BRIM,gap:0});
    const out=resolve('.local/zero-gap-brim.3mf');
    writeFileSync(out,exportProject(p,result));
    const info=execFileSync(slicer,['--info',out],{encoding:'utf8',timeout:60000});
    expect(info).toMatch(/manifold = yes/);
    expect(info).not.toMatch(/(?:open_edges|edges_fixed|facets_added|facets_removed) = [1-9]/);
  });
  it('opens an OBJ-derived model and brim as a manifold multipart 3MF', () => {
    mkdirSync('.local',{recursive:true});
    const mesh=box(), vertices=Array.from({length:mesh.vertices.length/3},(_,i)=>`v ${mesh.vertices.slice(i*3,i*3+3).join(' ')}`);
    const faces=Array.from({length:mesh.triangles.length/3},(_,i)=>`f ${mesh.triangles.slice(i*3,i*3+3).map(n=>n+1).join(' ')}`);
    const p=importProject('body.obj',strToU8(['o OBJ body',...vertices,...faces].join('\n')).slice().buffer);
    const out=resolve('.local/obj-brim.3mf');
    writeFileSync(out,exportProject(p,generateBrims(p,DEFAULT_BRIM)));
    const info=execFileSync(slicer,['--info',out],{encoding:'utf8',timeout:60000});
    expect(info).toMatch(/manifold = yes/); expect(info).not.toMatch(/open_edges/);
  });
  it('reopens configured brim parts and slices them as one layer of perimeters', () => {
    mkdirSync('.local', { recursive: true });
    const p = project([box(), box(70,20)]), result = generateBrims(p,DEFAULT_BRIM);
    writeFileSync('.local/two-objects.3mf', exportProject(p,result));
    const run = (...args: string[]) => execFileSync(slicer,args,{ encoding:'utf8',timeout:60000 });
    run('--export-3mf','--output',resolve('.local/slicer-roundtrip.3mf'),resolve('.local/two-objects.3mf'));
    const round=unzipSync(readFileSync('.local/slicer-roundtrip.3mf'));
    const config=strFromU8(round['Metadata/Slic3r_PE_model.config']);
    expect(config.match(/key="perimeters" value="99"/g)).toHaveLength(2);
    expect(config.match(/key="name" value="Rolling brim"/g)).toHaveLength(2);
    expect(config.match(/key="fill_density" value="0%"/g)).toHaveLength(2);
    expect(config.match(/key="top_solid_layers" value="0"/g)).toHaveLength(2);
    expect(config.match(/key="ensure_vertical_shell_thickness" value="disabled"/g)).toHaveLength(2);
    expect(config.match(/key="only_one_perimeter_first_layer" value="0"/g)).toHaveLength(2);
    expect(config.match(/type="object" key="elefant_foot_compensation" value="0"/g)).toHaveLength(2);
    run('--load',resolve('examples/validation.ini'),'--dont-arrange','--export-gcode','--output',resolve('.local/two-objects.gcode'),resolve('.local/two-objects.3mf'));
    const gcode=readFileSync('.local/two-objects.gcode','utf8');
    let x=0,y=0,z=0,type='',brimMoves=0,modelMoves=0;
    const firstFeatures: string[]=[];
    for(const line of gcode.split(/\r?\n/)) {
      if(line.startsWith(';TYPE:')) type=line.slice(6);
      if(!/^G[01] /.test(line)) continue;
      const fields=Object.fromEntries([...line.matchAll(/([XYZEF])([-+]?(?:\d+\.?\d*|\.\d+))/g)].map(m=>[m[1],Number(m[2])]));
      const px=x,py=y; x=fields.X??x; y=fields.Y??y; z=fields.Z??z;
      if(!(fields.E>0) || Math.hypot(x-px,y-py)<0.001) continue;
      const mx=(x+px)/2,my=(y+py)/2;
      const inside=(mx>=19.99&&mx<=40.01&&my>=19.99&&my<=40.01)||(mx>=69.99&&mx<=90.01&&my>=19.99&&my<=40.01);
      if(inside) modelMoves++;
      else {
        brimMoves++;
        expect(z).toBeCloseTo(0.2,4);
        expect(type).toMatch(/perimeter/i);
      }
      if(z===0.2&&firstFeatures.length<20) firstFeatures.push(inside?'model':'brim');
    }
    expect(brimMoves).toBeGreaterThan(100); expect(modelMoves).toBeGreaterThan(100);
    writeFileSync('.local/slicer-validation.json',JSON.stringify({version:gcode.match(/generated by ([^\r\n]+)/)?.[1],brimMoves,modelMoves,firstFeatures,firstLayer:0.2,overrideRoundtrip:true},null,2));
    const bytes=readFileSync('.local/slicer-roundtrip.3mf');
    expect(importProject('roundtrip.3mf',bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)).objects).toHaveLength(2);
  }, 90000);
  it('applies zero elephant-foot compensation to both model and brim despite a nonzero print profile', () => {
    mkdirSync('.local',{recursive:true});
    const p=project([box()]);
    writeFileSync('.local/compensation.3mf',exportProject(p,generateBrims(p,{...DEFAULT_BRIM,gap:1})));
    const files=unzipSync(readFileSync('.local/compensation.3mf'));
    files['Metadata/Slic3r_PE_model.config']=strToU8(strFromU8(files['Metadata/Slic3r_PE_model.config']).replace(/<metadata type="object" key="elefant_foot_compensation" value="0"\/>/g,''));
    writeFileSync('.local/compensation-control.3mf',zipSync(files));
    const bounds = [[0,false],[0.3,false],[0.3,true]].map(([value,control]) => {
      const out=resolve(`.local/compensation-${value}-${control}.gcode`);
      execFileSync(slicer,['--load',resolve('examples/validation.ini'),'--elefant-foot-compensation',String(value),'--dont-arrange','--export-gcode','--output',out,resolve(`.local/compensation${control?'-control':''}.3mf`)],{encoding:'utf8',timeout:60000});
      // Seams may vary between slicer runs. Compare the actual first-layer
      // extrusion bounds of BOTH body and brim, independent of start points.
      const regions=[{minX:Infinity,minY:Infinity,maxX:-Infinity,maxY:-Infinity},{minX:Infinity,minY:Infinity,maxX:-Infinity,maxY:-Infinity}];
      let x=0,y=0,z=0;
      for(const line of readFileSync(out,'utf8').split(/\r?\n/)) {
        if(!/^G[01] /.test(line)) continue;
        const fields=Object.fromEntries([...line.matchAll(/([XYZE])([-+]?(?:\d+\.?\d*|\.\d+))/g)].map(m=>[m[1],Number(m[2])]));
        const px=x,py=y; x=fields.X??x; y=fields.Y??y; z=fields.Z??z;
        if(z!==0.2 || !(fields.E>0) || Math.hypot(x-px,y-py)<0.001) continue;
        const mx=(x+px)/2,my=(y+py)/2, r=regions[mx>=20&&mx<=40&&my>=20&&my<=40?0:1];
        r.minX=Math.min(r.minX,x,px); r.minY=Math.min(r.minY,y,py); r.maxX=Math.max(r.maxX,x,px); r.maxY=Math.max(r.maxY,y,py);
      }
      return regions;
    });
    expect(bounds[0].every(r=>Number.isFinite(r.minX))).toBe(true);
    expect(bounds[1]).toEqual(bounds[0]);
    expect(bounds[2][0].minX).toBeGreaterThan(bounds[0][0].minX+0.1);
    expect(bounds[2][1].minX).toBeGreaterThan(bounds[0][1].minX+0.1);
  },90000);
  it('keeps rotated and mirrored instances aligned after a real slicer save', () => {
    mkdirSync('.local',{recursive:true});
    const input=archive(`<object id="1">${meshXml(box(0,0))}</object>`,'<item objectid="1" transform="0 1 0 -1 0 0 0 0 1 60 20 0"/><item objectid="1" transform="-1 0 0 0 1 0 0 0 1 120 20 0"/>');
    const p=importProject('transformed.3mf',input),result=generateBrims(p,DEFAULT_BRIM);
    writeFileSync('.local/transformed.3mf',exportProject(p,result));
    execFileSync(slicer,['--export-3mf','--output',resolve('.local/transformed-roundtrip.3mf'),resolve('.local/transformed.3mf')],{encoding:'utf8',timeout:60000});
    const bytes=readFileSync('.local/transformed-roundtrip.3mf'), round=importProject('round.3mf',bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));
    expect(round.objects).toHaveLength(2);
    const beforeOrdered=[...result.objects].sort((a,b)=>boundsOf(a.footprint).minX-boundsOf(b.footprint).minX);
    const afterOrdered=round.objects.map(o=>boundsOf(sliceMesh(o.parts[0].mesh,0.1))).sort((a,b)=>a.minX-b.minX);
    afterOrdered.forEach((afterBounds,i)=>{
      const beforeBounds=boundsOf(beforeOrdered[i].footprint);
      expect(afterBounds.minX).toBeCloseTo(beforeBounds.minX,3); expect(afterBounds.maxY).toBeCloseTo(beforeBounds.maxY,3);
    });
    const files=unzipSync(bytes), config=strFromU8(files['Metadata/Slic3r_PE_model.config']);
    expect(config.match(/value="Rolling brim"/g)).toHaveLength(2);
    const brimBounds=round.objects.flatMap(o=>o.parts.filter(p=>p.name==='Rolling brim').map(p=>boundsOf(sliceMesh(p.mesh,0.1)))).sort((a,b)=>a.minX-b.minX);
    brimBounds.forEach((b,i)=>{ expect(b.minX).toBeCloseTo(boundsOf(beforeOrdered[i].area).minX,3); expect(b.maxY).toBeCloseTo(boundsOf(beforeOrdered[i].area).maxY,3); });
  },90000);
});
