import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = path => readFileSync(resolve(root, path), 'utf8').replaceAll('\r\n', '\n');
const lock = JSON.parse(read('package-lock.json'));
const sections = [
  'Rolling Brim — third-party notices',
  'These packages retain their own licenses and copyright notices.\n' +
  'This inventory includes all runtime dependencies in package-lock.json, even\n' +
  'when only part of a package is included in the browser build. Build tools\n' +
  'remain under the licenses supplied in their installed packages.\n\n' +
  'Generated by npm run licenses; do not edit this file directly.',
];

for (const [path, entry] of Object.entries(lock.packages).sort(([a], [b]) => a.localeCompare(b))) {
  if (!path || entry.dev) continue;
  const pkg = JSON.parse(read(`${path}/package.json`));
  if (pkg.version !== entry.version) throw new Error(`${pkg.name}: run npm ci to install the locked version.`);
  const files = readdirSync(resolve(root, path)).filter(name => /^licen[cs]e(?:$|\.)/i.test(name)).sort();
  // These pinned packages omit the monorepo license from their npm archives.
  // Keep reviewed upstream copies in the repo rather than modifying node_modules.
  const chestnut = ['@chestnutlabs/gcode-bgcode', '@chestnutlabs/gcode-containers', '@chestnutlabs/toolpath-core'].includes(pkg.name);
  if (!files.length && !chestnut) throw new Error(`Missing license text for ${pkg.name}; review its distribution terms.`);
  const repository = typeof pkg.repository === 'string' ? pkg.repository : pkg.repository?.url;
  const source = (repository || pkg.homepage || '').replace(/^git\+/, '').replace(/\.git$/, '');
  let attribution = '';
  // Clipper's Boost license file has no copyright line. Preserve the notices
  // in its source headers as well as the port's author credit.
  if (pkg.name === 'clipper2-ts') {
    const notices = new Set();
    for (const file of readdirSync(resolve(root, path, 'src')).filter(name => name.endsWith('.ts')).sort()) {
      for (const match of read(`${path}/src/${file}`).matchAll(/^\*\s*(Copyright\s*:[^\r\n*]+)/gm)) notices.add(match[1].trim());
    }
    if (!notices.size) throw new Error('Clipper copyright headers changed; review its attribution.');
    attribution = `\n${pkg.author}\n${[...notices].sort().join('\n')}\n`;
  }
  sections.push(`${pkg.name} ${pkg.version} — ${pkg.license}\n${source}\n${attribution}\n` +
    (files.length ? files.map(file => read(`${path}/${file}`).trimEnd()).join('\n\n') : read('licenses/chestnutlabs-MIT.txt').trimEnd()) +
    (pkg.name === '@chestnutlabs/gcode-bgcode' ? '\n\nMeatPack decoder attribution:\n' + read('licenses/meatpack-MIT.txt').trimEnd() + '\n\nHeatshrink decoder attribution:\n' + read('licenses/heatshrink-ISC.txt').trimEnd() : ''));
}

const outputs = {
  'public/LICENSE.txt': read('LICENSE'),
  'public/THIRD_PARTY_NOTICES.txt': sections.join(`\n\n${'='.repeat(72)}\n\n`) + '\n',
};
for (const [path, content] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) {
    if (read(path) !== content) throw new Error(`${path} is stale. Run npm run licenses and commit the result.`);
  } else writeFileSync(resolve(root, path), content);
}
console.log(process.argv.includes('--check') ? 'License notices are current.' : 'Updated hosted license and third-party notices.');
