import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Box, Check, ChevronDown, Circle, CircleHelp, Download, Focus, Layers3, LoaderCircle, LockKeyhole, Maximize2, RotateCcw, ScanLine, Settings2, SlidersHorizontal, Upload, X } from 'lucide-react';
import FirstLayerView from './components/FirstLayerView';
import ModelView from './components/ModelView';
import EmptyIllustration from './components/EmptyIllustration';
import { DEFAULT_BRIM, SLICER_NAMES, type SlicerFormat, DIAMETER_STEP, MAX_DIAMETER, MIN_DIAMETER, type BrimResult, type BrimSettings, type Project, type WorkerRequest, type WorkerResponse } from './core/types';
import { formatSampleHeight, sampleHeights, MIN_LAYER_HEIGHT, MAX_LAYER_HEIGHT } from './core/first-layer';
import sampleUrl from '../examples/clearance-test-plate.stl?url';

function NumberControl({ label, value, min, max, sliderMax = max, step, onChange, description, unit = 'mm' }: { label: string; value: number; min: number; max: number; sliderMax?: number; step: number; onChange: (n: number) => void; description: string; unit?: string }) {
  const [draft, setDraft] = useState(String(value)); useEffect(() => setDraft(String(value)), [value]);
  const id = label.replaceAll(' ', '-').toLowerCase();
  const sliderValue = Math.max(min, Math.min(sliderMax, value));
  const commit = () => { const n = Number(draft); if (draft.trim() && Number.isFinite(n)) { const next = Math.max(min, Math.min(max, n)); setDraft(String(next)); onChange(next); } else setDraft(String(value)); };
  return <div className="number-control"><div className="control-heading"><label htmlFor={id}>{label}</label><div className="number-box"><input id={id} type="number" value={draft} min={min} max={max} step={step} onChange={e => setDraft(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === 'Enter') { commit(); e.currentTarget.blur(); } }}/><span>{unit}</span></div></div><input className="range-input" aria-label={`${label} slider`} type="range" min={min} max={sliderMax} step={step} value={sliderValue} onChange={e => onChange(Number(e.target.value))} style={{ '--range-fill': `${(sliderValue-min)/(sliderMax-min)*100}%` } as React.CSSProperties}/><p className="control-description">{description}</p></div>;
}
function Toggle({ label, description, checked, onChange, count }: { label: string; description: string; checked: boolean; onChange: () => void; count?: number }) {
  return <label className="toggle-row"><span><span className="toggle-title">{label}{count !== undefined && <span className="count-badge">{count}</span>}</span><span className="toggle-description">{description}</span></span><input type="checkbox" checked={checked} onChange={onChange} role="switch"/><span className="toggle-track" aria-hidden="true"/></label>;
}
export default function App() {
  const [project, setProject] = useState<Omit<Project,'source'> | null>(null), [result, setResult] = useState<BrimResult | null>(null);
  const [settings, setSettings] = useState<BrimSettings>(DEFAULT_BRIM), [enabled, setEnabled] = useState<string[]>([]), [selected, setSelected] = useState<string | null>(null);
  const [outputFormat, setOutputFormat] = useState<SlicerFormat>('prusa'), [changingPlate, setChangingPlate] = useState(false);
  const plateRequest = useRef<number | null>(null), skipGeneration = useRef(false);
  const [prepared, setPrepared] = useState<{ url: string; name: string } | null>(null);
  const [status, setStatus] = useState(''), [error, setError] = useState(''), [toast, setToast] = useState(''), [dragging, setDragging] = useState(false);
  const [maximizing, setMaximizing] = useState(false), [diameterNotice, setDiameterNotice] = useState('');
  const [view, setView] = useState<'2d'|'3d'>('2d'), [probe, setProbe] = useState(false), [compare, setCompare] = useState(false), [showBrim, setShowBrim] = useState(true), [showUncovered, setShowUncovered] = useState(true), [fitKey, setFitKey] = useState(0), [help, setHelp] = useState(false), [detailsOpen, setDetailsOpen] = useState(false);
  const input = useRef<HTMLInputElement>(null), worker = useRef<Worker | null>(null), request = useRef(0), dragDepth = useRef(0), filename = useRef('model');
  const maximizeRequest = useRef<number | null>(null), appliedSettings = useRef<BrimSettings | null>(null);
  const send = (message: WorkerRequest) => worker.current?.postMessage(message);
  useEffect(() => () => worker.current?.terminate(), []);
  useEffect(() => () => { if (prepared) URL.revokeObjectURL(prepared.url); }, [prepared]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 5000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { if (!help) return; const listener = (e: KeyboardEvent) => { if (e.key === 'Escape') setHelp(false); }; window.addEventListener('keydown',listener); return () => window.removeEventListener('keydown',listener); }, [help]);
  const load = useCallback(async (file: File) => {
    if (!/\.(stl|obj|3mf)$/i.test(file.name)) { setError('Choose an STL, OBJ or 3MF file.'); return; }
    if (file.size > 200_000_000) { setError('Choose a file smaller than 200 MB.'); return; }
    worker.current?.terminate(); const id = ++request.current; setProject(null); setResult(null); setPrepared(null); setError(''); setStatus('Reading model geometry…'); setSelected(null); filename.current = file.name.replace(/\.(stl|obj|3mf)$/i,'');
    setMaximizing(false); setDiameterNotice(''); maximizeRequest.current = null; appliedSettings.current = null; plateRequest.current = null; setChangingPlate(false); skipGeneration.current = false;
    const instance = new Worker(new URL('./core/worker.ts', import.meta.url), { type: 'module' }); worker.current = instance;
    instance.onmessage = ({ data }: MessageEvent<WorkerResponse>) => {
      if (data.id !== request.current) return;
      if (data.type === 'error') {
        if (plateRequest.current === data.id) { plateRequest.current = null; skipGeneration.current = true; setChangingPlate(false); }
        setStatus(''); setMaximizing(false);
        if (maximizeRequest.current === data.id) { setDiameterNotice(data.message); maximizeRequest.current = null; }
        else { setError(data.message); setResult(null); setPrepared(null); }
      }
      if (data.type === 'loaded') { plateRequest.current = null; setChangingPlate(false); if (data.project.format && data.project.format !== 'generic') setOutputFormat(data.project.format); else setOutputFormat(current => current === 'prusa3' ? 'prusa' : current); setProject(data.project); setEnabled(data.project.objects.map(o => o.id)); setFitKey(n => n + 1); setStatus('Building rolling brims…'); }
      if (data.type === 'generated') { setResult(data.result); setStatus(''); }
      if (data.type === 'maximizing') setStatus(data.progress.stage === 'verifying' ? `Verifying ${data.progress.diameter.toFixed(2)} mm…` : `Optimizing diameter… testing ${data.progress.diameter.toFixed(2)} mm`);
      if (data.type === 'maximized') {
        setMaximizing(false); setStatus(''); maximizeRequest.current = null;
        const outcome = data.outcome;
        if (outcome.status === 'found') {
          appliedSettings.current = outcome.result.settings;
          setSettings(outcome.result.settings); setResult(outcome.result); setPrepared(null);
          setDiameterNotice(outcome.atLimit ? `Maximum supported diameter reached: ${MAX_DIAMETER} mm. All enabled footprints covered.` : `Optimized to ${outcome.result.settings.diameter.toFixed(2)} mm. All enabled footprints covered.`);
        } else if (outcome.status === 'no-solution') setDiameterNotice(`Cannot cover all enabled footprints at the minimum diameter (${MIN_DIAMETER} mm): ${outcome.uncovered} uncovered. Diameter unchanged.`);
        else setDiameterNotice('Enable an object with a first-layer footprint to optimize its diameter.');
      }
      if (data.type === 'cancelled') { setMaximizing(false); setStatus(''); maximizeRequest.current = null; setDiameterNotice('Search cancelled. Diameter unchanged.'); }
      if (data.type === 'exported') { const blob = new Blob([data.bytes.slice().buffer as ArrayBuffer], { type: 'model/3mf' }); const url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = data.filename || `${filename.current}-rolling-brim.3mf`; setPrepared({ url, name: link.download }); document.body.appendChild(link); link.click(); link.remove(); setStatus(''); setToast(`Download started. Open the 3MF as a project in ${SLICER_NAMES[data.slicer || 'prusa']}.`); }
    };
    instance.onerror = e => { if (worker.current === instance) { setError(e.message || 'Processing stopped. Try opening the model again.'); setStatus(''); setMaximizing(false); setResult(null); setPrepared(null); } };
    try { const bytes = await file.arrayBuffer(); if (id === request.current) instance.postMessage({ type: 'load', id, name: file.name, bytes } satisfies WorkerRequest, [bytes]); } catch (e) { if (id === request.current) { setError(String(e)); setStatus(''); } }
  }, []);
  useEffect(() => {
    if (!project || changingPlate) return;
    if (skipGeneration.current) { skipGeneration.current = false; return; }
    if (!project.objects.length) { setStatus(''); return; }
    // The optimizer already returned the full, verified preview for these settings.
    if (appliedSettings.current === settings) { appliedSettings.current = null; return; }
    appliedSettings.current = null; maximizeRequest.current = null; setMaximizing(false); setDiameterNotice('');
    setPrepared(null); const id = ++request.current; setStatus('Updating brim geometry…'); setError('');
    const timer = setTimeout(() => send({ type: 'generate', id, settings, enabled }), 220); return () => clearTimeout(timer);
  }, [project, settings, enabled, changingPlate]);
  const update = <K extends keyof BrimSettings>(key: K, value: BrimSettings[K]) => setSettings(s => ({ ...s, [key]: value }));
  const sample = async () => { try { const response = await fetch(sampleUrl); if (!response.ok) throw new Error('Could not load the example.'); setSettings(DEFAULT_BRIM); await load(new File([await response.blob()], 'clearance-test-plate.stl')); } catch(e) { setError(String(e)); } };
  const canExport = !!result?.objects.some(o => o.area.length) && !status && !error;
  const canMaximize = !!result?.objects.some(o => enabled.includes(o.id) && o.footprint.length) && !status && !error;
  const maximize = () => {
    if (!canMaximize) return;
    const id = ++request.current; maximizeRequest.current = id;
    setMaximizing(true); setDiameterNotice(''); setStatus('Optimizing diameter…');
    send({ type: 'maximize', id, settings, enabled });
  };
  const cancelMaximize = () => { send({ type: 'cancel', id: ++request.current }); };
  const download = () => { if (!canExport) return; setStatus('Packaging 3MF project…'); send({ type: 'export', id: ++request.current, settings, enabled, format: outputFormat }); };
  const changePlate = (plateId: string) => {
    if (!project || plateId === project.activePlateId) return;
    const id = ++request.current; plateRequest.current = id; appliedSettings.current = null; maximizeRequest.current = null;
    setChangingPlate(true); setMaximizing(false); setDiameterNotice(''); setSelected(null); setResult(null); setPrepared(null); setError(''); setStatus('Reading selected plate…');
    send({ type: 'plate', id, plateId });
  };
  const nativeProject = project?.format && project.format !== 'generic';
  const slicerName = SLICER_NAMES[outputFormat];
  const notices = [...(project?.warnings || []), ...(result?.warnings || []), ...(result?.objects.flatMap(o => o.warnings.map(w => `${project?.objects.find(p => p.id === o.id)?.name}: ${w}`)) || [])];
  const area = result?.objects.reduce((sum,o) => sum + o.areaMm2,0) || 0;
  const heights = sampleHeights(result?.settings.height ?? settings.height);
  const uncoveredCount = result?.objects.reduce((sum,o) => sum + o.uncovered.length,0) ?? 0;
  const brimCount = result?.objects.filter(o => o.area.length).length ?? 0;
  return <div className="app-shell" onDragEnter={e => { e.preventDefault(); if (e.dataTransfer.types.includes('Files')) { dragDepth.current++; setDragging(true); } }} onDragOver={e => e.preventDefault()} onDragLeave={e => { e.preventDefault(); if (--dragDepth.current <= 0) setDragging(false); }} onDrop={e => { e.preventDefault(); dragDepth.current = 0; setDragging(false); if (e.dataTransfer.files.length > 1) { setError('Open one STL, OBJ or 3MF at a time. A 3MF can contain multiple objects.'); return; } const file = e.dataTransfer.files[0]; if (file) void load(file); }}>
    <input ref={input} className="visually-hidden" type="file" accept=".stl,.obj,.3mf" aria-label="Open STL, OBJ or 3MF" onChange={e => { const file = e.target.files?.[0]; if (file) void load(file); e.target.value = ''; }}/>
    <header className="app-header"><div className="brand"><img src={`${import.meta.env.BASE_URL}favicon.svg`} alt=""/><div>Rolling Brim<span>FIRST LAYER, RECONSIDERED.</span></div><span className="version-tag">3MF</span></div><div className="header-actions"><span className="local-label"><LockKeyhole size={13}/> Local to your browser</span><button className="icon-button help-button" aria-label="How Rolling Brim works" onClick={() => setHelp(true)}><CircleHelp size={19}/></button><button className="button button-primary export-button" disabled={!canExport} onClick={download}><Download size={17}/>{project?.plates ? 'Download selected plate' : 'Download 3MF'}</button></div></header>
    <div className="workbench"><aside className="sidebar"><div className="sidebar-top"><span className="eyebrow">BRIM WORKSPACE</span><SlidersHorizontal size={16}/></div>
      <button className={`source-card ${project ? 'has-file' : ''}`} onClick={() => input.current?.click()}><span className="source-icon">{project ? <Box size={20}/> : <Upload size={20}/>}</span><span className="source-text"><strong title={project?.name}>{project?.name || 'Open a model'}</strong><span>{project ? `${project.objects.length} object${project.objects.length === 1 ? '' : 's'} · STL / OBJ / 3MF` : 'STL, OBJ or 3MF · three slicer formats'}</span></span><ArrowUpRight size={16}/></button>
      {project && <div className="project-controls">
        {project.plates && <label>Working plate<select aria-label="Working plate" value={project.activePlateId} disabled={changingPlate} onChange={e => changePlate(e.target.value)}>{project.plates.map(plate => <option key={plate.id} value={plate.id}>{plate.name} · {plate.objectCount} object{plate.objectCount === 1 ? '' : 's'}</option>)}</select><span>Only this plate is exported. Brim controls are shared across plates.</span></label>}
        <label>Output slicer<select aria-label="Output slicer" value={outputFormat} disabled={!!nativeProject || !!status} onChange={e => { setOutputFormat(e.target.value as SlicerFormat); setPrepared(null); }}>{Object.entries(SLICER_NAMES).filter(([id]) => id !== 'prusa3' || project.format === 'prusa3').map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select><span>{project.format === 'prusa3' ? 'Experimental: native 3.0.0-alpha12 projects only. Unsupported features are rejected.' : nativeProject ? 'Uses the original slicer to preserve project settings.' : 'Open the download as a project to keep brim part settings.'}</span></label>
      </div>}
      <section className="settings-section"><div className="section-label"><span>01</span><h2>Shape the brim</h2></div>
        <NumberControl label="Rolling diameter" value={settings.diameter} min={MIN_DIAMETER} max={MAX_DIAMETER} sliderMax={50} step={DIAMETER_STEP} onChange={v => update('diameter',v)} description="Larger circles stay out of tighter gaps."/>
        <div className="diameter-optimizer"><button className="maximize-button" disabled={!maximizing && !canMaximize} onClick={maximizing ? cancelMaximize : maximize} title="Find the largest rolling diameter that gives every enabled footprint adjacent brim.">{maximizing ? <X size={13}/> : <Maximize2 size={13}/>}<span>{maximizing ? 'Cancel search' : 'Optimize diameter'}</span></button>{diameterNotice && <p className="diameter-notice" role="status">{diameterNotice}</p>}</div>
        <NumberControl label="Brim width" value={settings.width} min={0.5} max={20} sliderMax={10} step={0.5} onChange={v => update('width',v)} description="Width measured from the rolled boundary."/><NumberControl label="Separation gap" value={settings.gap} min={-0.2} max={1} step={0.01} onChange={v => update('gap',v)} description={settings.gap < 0 ? 'Overlap the model for a stronger bond.' : 'Space between the rolled outline and brim.'}/></section>
      <section className="settings-section regions-section"><div className="section-label"><span>02</span><h2>Choose where it goes</h2></div><div className="always-row"><span><Circle size={14}/>Reachable outside</span><span className="always-badge">ALWAYS ON</span></div><Toggle label="Inside enclosed holes" checked={settings.holes} onChange={() => update('holes',!settings.holes)} count={result?.regions.holes} description="Only where the rolling circle fits."/><Toggle label="Inside narrow-entry pockets" checked={settings.pockets} onChange={() => update('pockets',!settings.pockets)} count={result?.regions.pockets} description="Place the circle beyond a tight entrance."/><div className="region-note">Narrow slots stay clear within each object. Objects are processed independently.</div></section>
      <details className="print-details"><summary><span><Settings2 size={15}/> First layer & part settings</span><ChevronDown size={15}/></summary><div className="print-settings-body"><NumberControl label="First-layer height" value={settings.height} min={MIN_LAYER_HEIGHT} max={MAX_LAYER_HEIGHT} step={0.01} onChange={v => update('height',v)} description={`Footprint sampled at Z ${(settings.height/2).toFixed(3)} mm. Brim thickness ${settings.height.toFixed(2)} mm.`}/>{project?.suggestedHeight && <button className="sample-link height-link" onClick={() => update('height',project.suggestedHeight!)}>Use file’s {project.suggestedHeight} mm first layer</button>}<NumberControl label="Perimeters" value={settings.perimeters} min={1} max={99} step={1} unit="" onChange={v => update('perimeters',Math.round(v))} description="99 fills the brim with perimeter loops wherever they fit."/><p>Brim parts get 0% infill, no top/bottom shells, no gap fill and no ironing. Speed follows your slicer settings.</p><p>Elephant-foot compensation is set to 0 for each object, covering both the model and its brim.</p></div></details>
      {project && <section className="objects-section"><div className="section-label"><span>03</span><h2>Objects</h2></div><p>Check to add a brim. Click a name to highlight.</p>{project.objects.map(o => <div className={`object-row ${selected === o.id ? 'selected' : ''}`} key={o.id}><input type="checkbox" aria-label={`Add brim to ${o.name}`} checked={enabled.includes(o.id)} onChange={() => setEnabled(ids => ids.includes(o.id) ? ids.filter(id => id !== o.id) : [...ids,o.id])}/><button onClick={() => setSelected(selected === o.id ? null : o.id)} aria-pressed={selected === o.id}><Box size={14}/><span>{o.name}<small>{o.parts.filter(p => p.kind === 'ModelPart').length} model part(s)</small></span></button></div>)}</section>}
      <button className="reset-settings" onClick={() => setSettings(DEFAULT_BRIM)}><RotateCcw size={13}/>Reset brim settings</button></aside>
      <main className="main-panel"><div className="workspace-toolbar"><div className="view-tabs" role="tablist" aria-label="Preview mode"><button role="tab" aria-selected={view === '3d'} className={view === '3d' ? 'active' : ''} onClick={() => setView('3d')}><Box size={16}/>3D model</button><button role="tab" aria-selected={view === '2d'} className={view === '2d' ? 'active' : ''} onClick={() => setView('2d')}><Layers3 size={16}/>Footprint</button></div><div className="toolbar-actions">{view === '2d' && <button className={`toolbar-button ${probe ? 'selected' : ''}`} onClick={() => setProbe(!probe)} aria-label="Circle sweep" title="Show where the full rolling circle fits. Unaffected by brim width or separation gap. Preview only." aria-pressed={probe}><Circle size={15}/><span>Circle sweep</span></button>}<button className="toolbar-button" aria-label="Fit view" disabled={!result} onClick={() => setFitKey(n => n+1)}><Focus size={16}/><span>Fit view</span></button></div></div>
      {error && <div className="error-banner" role="alert"><span>{error}</span></div>}
      <div className={`viewer-surface ${status ? 'is-updating' : ''}`}>{project && result ? <>{view === '2d' ? <FirstLayerView result={result} bed={project.bed} showBrim={showBrim} showUncovered={showUncovered} compare={compare} probe={probe} fitKey={fitKey} selected={selected}/> : <ModelView project={project} result={result} showBrim={showBrim} fitKey={fitKey} selected={selected}/>}<div className="viewer-heading"><span className="eyebrow">{view === '2d' ? 'FIRST-LAYER FOOTPRINT' : 'MODEL & BRIM PARTS'}</span><span>{view === '2d' ? `Sample Z ${(result.settings.height/2).toFixed(3)} mm · layer ${result.settings.height.toFixed(2)} mm` : `Geometry preview · slice in ${slicerName}`}</span></div><div className="viewer-legend"><span><i className="swatch model-swatch"/>{compare && view === '2d' ? `Brim reference · ${formatSampleHeight(heights.middle)} mm` : 'Model'}</span><button onClick={() => setShowBrim(!showBrim)} aria-pressed={showBrim} className={showBrim ? '' : 'muted'}><i className="swatch brim-swatch"/>Rolling brim</button>{view === '2d' && uncoveredCount > 0 && <button onClick={() => setShowUncovered(!showUncovered)} aria-pressed={showUncovered} className={showUncovered ? '' : 'muted'} title="Footprints without adjacent brim from their own object, allowing for the selected separation gap. Only checked objects are included. Click to toggle highlighting."><i className="swatch uncovered-swatch"/>Uncovered ({uncoveredCount})</button>}{compare && view === '2d' && <><span className="lower-outline">Near bed · {formatSampleHeight(heights.bottom)} mm</span><span className="upper-outline">Layer top · {formatSampleHeight(heights.top)} mm</span></>}</div></> : project ? <div className="empty-state"><Layers3 size={40}/><h2>{status ? 'Preparing the preview…' : project.objects.length ? 'Preview unavailable' : 'No printable objects on this plate'}</h2><p>{status ? 'Using the current brim controls.' : project.objects.length ? 'Check the model notes or adjust the first-layer settings.' : 'Choose another working plate to continue.'}</p></div> : <div className="empty-state"><EmptyIllustration/><span className="eyebrow">A LITTLE MORE HOLD. A LOT LESS HASSLE.</span><h1>Give your model a better start.</h1><p>Shape a rolling brim. Keep the tight gaps clear.<br/>Open it in PrusaSlicer 2.x, Bambu Studio or OrcaSlicer<br/>with every brim already attached.</p><button className="button button-primary" onClick={() => input.current?.click()} disabled={!!status}><Upload size={17}/>Open STL, OBJ or 3MF</button><span className="drop-hint">or drop a model anywhere</span><button className="sample-link" onClick={() => void sample()} disabled={!!status}>Try the holes & pockets test plate <ArrowUpRight size={14}/></button><div className="empty-local"><LockKeyhole size={13}/>Your file stays in this browser. No upload required.</div></div>}{status && <div className="processing-status" role="status"><LoaderCircle className="spin" size={15}/>{status}</div>}</div>
      <div className="layer-bar compact-layer-bar">
        <div className="layer-title"><ScanLine size={16}/><span>First layer <strong>{settings.height.toFixed(2)} mm</strong></span></div>
        <span className="compact-metrics">{project ? `${project.objects.length} object${project.objects.length === 1 ? '' : 's'} · ${brimCount} brim${brimCount === 1 ? '' : 's'}` : 'Waiting for a model'}</span>
        <label className="outline-control" title="Compare the model near the bed and near the top of its first layer. The brim uses the middle of that layer."><input type="checkbox" disabled={!result} checked={compare} aria-describedby={compare && view === '2d' ? 'outline-explanation' : undefined} onChange={e => { setCompare(e.target.checked); setView('2d'); }}/>Compare layer outlines</label>
        <button className="details-toggle" aria-expanded={detailsOpen} aria-controls="model-details" onClick={() => setDetailsOpen(open => !open)}>Details{!!notices.length && <span className="count-badge" aria-label={`${notices.length} model notes`}>{notices.length}</span>}<ChevronDown size={14}/></button>
      </div>
      {compare && view === '2d' && result && <div className="outline-explanation" id="outline-explanation"><strong>Does the base change within the first layer?</strong> Gray is the brim reference at Z={formatSampleHeight(heights.middle)} mm. Blue cuts near the bed ({formatSampleHeight(heights.bottom)} mm); pink cuts near the layer top ({formatSampleHeight(heights.top)} mm). The cuts sit slightly inside the layer to avoid tiny mesh offsets. Matching edges show blue through the pink dashes; separated lines reveal a slope. A missing color means no section exists at that height.</div>}
      {prepared && <p className="prepared-download compact-download">3MF ready. <a href={prepared.url} download={prepared.name}>Save prepared 3MF</a> if the download did not start.</p>}
      <div id="model-details" className="result-panel" hidden={!detailsOpen}><div className="result-heading"><div><span className="eyebrow">ADDED BRIM</span><h2>{result ? 'A part of every print.' : 'Your brim, at a glance.'}</h2></div><span className={`result-status ${result && !status ? 'ready' : ''}`}>{status ? <LoaderCircle size={13} className="spin"/> : result ? <Check size={13}/> : <Circle size={12}/>}{status ? 'Calculating' : result ? 'Geometry ready' : 'Waiting for a file'}</span></div><div className="metrics"><div><span>Model objects</span><strong>{project?.objects.length ?? '—'}</strong></div><div><span>Brim parts</span><strong>{result ? result.objects.filter(o => o.area.length).length : '—'}</strong></div><div><span>Brim area</span><strong>{result ? Math.round(area) : '—'}<small>mm²</small></strong></div><div><span>Sample height</span><strong>{(settings.height/2).toFixed(3)}<small>mm</small></strong></div></div><div className="result-footnote">Open the download as a project to retain part settings. {slicerName} determines toolpaths and print order; brim-first is not guaranteed.</div>{!!notices.length && <details className="review-notes" open><summary><span><CircleHelp size={14}/>Model & slicing notes <span className="count-badge">{notices.length}</span></span><ChevronDown size={14}/></summary><ul>{notices.map((note,i) => <li key={i}>{note}</li>)}</ul></details>}</div></main></div>
    <footer className="app-footer"><span>ROLLING BRIM <span className="footer-divider">/</span> 3MF WORKSPACE</span><span><a href={`${import.meta.env.BASE_URL}LICENSE.txt`}>MIT license</a><span className="footer-divider">·</span><a href={`${import.meta.env.BASE_URL}THIRD_PARTY_NOTICES.txt`}>Third-party notices</a><span className="footer-divider">·</span>All dimensions in mm</span></footer>
    {dragging && <div className="drop-overlay"><div><Upload size={40}/><h2>Drop your model here</h2><p>STL, OBJ or 3MF · ready for a rolling brim</p></div></div>}{toast && <div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {help && <div className="modal-backdrop" onClick={() => setHelp(false)}><section className="help-dialog" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e => e.stopPropagation()}><button className="icon-button modal-close" aria-label="Close help" onClick={() => setHelp(false)} autoFocus><X size={20}/></button><span className="eyebrow">THE ROLLING BRIM</span><h2 id="help-title">Adhesion with room to move.</h2><p>A virtual circle traces a boundary around each object. The brim grows outward from that boundary, following its curves across narrow gaps to connect pieces within the same object.</p><dl><div><dt>A slice through the first layer</dt><dd>At a 0.2 mm first-layer height, the footprint is sampled at Z=0.1 mm. Compare layer outlines to inspect the model near the bed (blue) and near the layer top (pink). Overlapping outlines mean the wall stays in the same place; separated outlines show a slope or overhang. The comparison does not change the brim geometry.</dd></div><div><dt>Holes and pockets</dt><dd>Enable these independently. The circle must fit inside; narrow slots stay clear.</dd></div><div><dt>Ready for your slicer</dt><dd>Each selected object gets a named Rolling brim part with its own perimeter and infill settings. Open the 3MF as a project and use the same first-layer height.</dd></div><div><dt>Working with plates</dt><dd>Choose one plate from a Bambu Studio, OrcaSlicer or supported PrusaSlicer 3.0 alpha12 project. The download contains that plate and all its objects. Checkboxes choose which objects receive brims. Switching plates starts from the original file and uses the same brim controls; edits are not accumulated across plates.</dd></div><div><dt>Multiple objects</dt><dd>Each entry in the Objects panel is processed on its own and keeps its own brim part. Pieces within one object can connect. Separate objects do not affect each other, and overlapping brims are left unchanged for you to arrange in the slicer. Existing project settings are preserved for supported PrusaSlicer 2.x, PrusaSlicer 3.0 alpha12, Bambu Studio and OrcaSlicer 3MFs, with elephant-foot compensation set to 0 for every object and its brim.</dd></div></dl><p className="help-note">The preview shows mesh geometry. Slicer compensation, native brims, supports and toolpath planning can change the final printed result. Part list order does not guarantee brim-first printing.</p><button className="button button-primary" onClick={() => setHelp(false)}>Back to the workbench</button></section></div>}
  </div>;
}
